services:
  - type: web
    name: food-order
    env: node
    buildCommand: npm install && npm run build:h5
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
