-- ============================================
-- 点餐小程序 Supabase 数据库初始化脚本
-- 在 Supabase SQL Editor 中粘贴执行即可
-- ============================================

-- 1. 菜品表
CREATE TABLE IF NOT EXISTS dishes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  image TEXT DEFAULT '',
  category_id INT NOT NULL DEFAULT 1,
  status TEXT DEFAULT 'available',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 订单表
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL,
  items JSONB DEFAULT '[]',
  total_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'pending',
  create_time BIGINT NOT NULL,
  remark TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 开启实时同步（Realtime）
ALTER PUBLICATION supabase_realtime ADD TABLE dishes;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;

-- 4. 插入默认菜品
INSERT INTO dishes (name, description, price, image, category_id, status) VALUES
('黄焖鸡米饭',   '鲜嫩鸡腿肉，搭配青椒香菇，汤汁浓郁', 22, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=chinese+braised+chicken+clay+pot+rice&image_size=square', 1, 'available'),
('红烧牛肉面',   '大块牛腩慢炖，汤头香浓', 25, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=braised+beef+noodle+soup+chinese&image_size=square', 1, 'available'),
('宫保鸡丁饭',   '鸡肉丁配花生米，麻辣鲜香', 20, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=kung+pao+chicken+rice+chinese&image_size=square', 2, 'available'),
('番茄炒蛋盖饭', '家常美味，酸甜可口', 16, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=tomato+egg+rice+chinese&image_size=square', 2, 'available'),
('凉拌黄瓜',     '清脆爽口，蒜香开胃', 8, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=chinese+cucumber+salad&image_size=square', 3, 'available'),
('皮蛋豆腐',     '嫩滑豆腐配皮蛋，清爽解暑', 10, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=century+egg+tofu&image_size=square', 3, 'available'),
('冰可乐',       '冰镇可乐，解渴必备', 5, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=iced+coca+cola&image_size=square', 4, 'available'),
('珍珠奶茶',     'Q弹珍珠配浓郁奶茶', 12, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=bubble+milk+tea&image_size=square', 4, 'available'),
('抹茶蛋糕',     '日式抹茶，绵密香甜', 15, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=matcha+cake+slice&image_size=square', 5, 'available'),
('芒果布丁',     '鲜芒果配嫩滑布丁', 12, 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mango+pudding&image_size=square', 5, 'available');

-- 5. 设置行级安全策略（RLS）
-- 允许所有人读写（因为你这是两个人的私用小程序）
ALTER TABLE dishes ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on dishes" ON dishes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on orders" ON orders FOR ALL USING (true) WITH CHECK (true);
